### ISSUE TITLE
Univariate case

### ISSUE THREAD

**Issue by MateusMaiaDS** [theodds/SoftBART#4]
Hi all,

How I am suppose to do the univariate case. I keep receiving this error message?

``` Error in glmnet(x, y, weights = weights, offset = offset, lambda = lambda,  : 
  x should be a matrix with 2 or more columns
```

**Comment by theodds** [comment]
Hi Mateus,

The first thing I would say is that, if you have only one predictor, then the payoff for using SBART is minimal, and that a basis function expansion of some sort will probably be faster and more performant. 

Now, if you accept that and still want to use SBART for whatever reason, you can do so by doing `cbind(x,x)` as the predictor matrix. That will have the same affect as fitting the univariate model.
