### ISSUE TITLE
Dirichlet prior

### ISSUE THREAD

**Issue by Mingyang-Cai** [theodds/SoftBART#9]
Thanks for the wonderful package. The package allows sparsity by specifying a Dirichlet prior. However, all variables are assigned with equal weights in the Dirichlet prior, e.g. X1, X2, ..., Xp ~ D(1, ..., 1). Is it possible to assign different weights for each variable? for example, X1, X2, X3 ~ D(1, 0.5, 0.75).

Thanks again.

**Comment by theodds** [comment]
Sadly no, although you can sort of hack this by including duplicates of some columns perhaps; e.g., two columns with X2, three with X3, and four with X1.
